apiVersion: v1
kind: Pod
metadata:
  name: cache-producer
spec:
  volumes:
    - name: cache-volume
      hostPath:
        path: /mnt/cache
        type: DirectoryOrCreate
  containers:
    - name: cache-writer
      image: busybox
      command: ["sh", "-c", "echo 'cache data' > /cache/data.txt && sleep 3600"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
---
apiVersion: v1
kind: Pod
metadata:
  name: cache-consumer
spec:
  volumes:
    - name: cache-volume
      hostPath:
        path: /mnt/cache
        type: Directory
  containers:
    - name: cache-reader
      image: busybox
      command:
        ["sh", "-c", "echo 'Reading:' && cat /cache/data.txt && sleep 3600"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
