apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_DB_USER: "fast_api_project"
  POSTGRES_DB_PASSWORD: "123456"
  DATABASE_URL: "postgresql://fast_api_project:123456@postgres-service:5432/database"
